// Bridges the bindings generated by `wrangler types` (interface Env, in
// worker-configuration.d.ts) into the global CloudflareEnv interface that
// @opennextjs/cloudflare's getCloudflareContext() returns.
//
// Declaration merging means CloudflareEnv gains every binding declared in wrangler.jsonc,
// so `wrangler types` remains the single source of truth. Re-run `npm run cf-typegen`
// after changing wrangler.jsonc.

declare global {
  interface CloudflareEnv extends Env {
    // Secrets are not part of wrangler.jsonc, so they are declared here.
    // Set locally in .dev.vars, in production via `wrangler secret put`.
    INGEST_TOKEN: string;
  }
}

export {};
