"use client";

import { useEffect, useId, useState } from "react";

/**
 * A Mermaid diagram, drawn in the browser.
 *
 * Class diagrams are the natural way to answer "how do these classes relate", and until this
 * existed a ```mermaid fence rendered as a wall of arrows-as-text -- present in the page, and
 * useless to look at.
 *
 * Mermaid is imported lazily, inside the effect. It is by far the heaviest thing this app can
 * load, and most prep pages contain no diagram at all; a static import would put it in the
 * bundle for every page, including the job board.
 *
 * The source is rendered, never trusted as markup: `mermaid.render` returns SVG it generated
 * from a grammar, and the failure branch shows the original text as text.
 */
export function Mermaid({ chart }: { chart: string }) {
  const [svg, setSvg] = useState<string | null>(null);
  const [failed, setFailed] = useState(false);
  /*
    Mermaid needs a DOM id unique to this diagram, and it must be stable across re-renders or
    each render leaks another orphan <svg> into the document.

    useId rather than a random string: random is impure in render and gives the server and the
    client different ids, which is a hydration mismatch. The colons React puts in its ids are
    not valid in a CSS selector, and Mermaid builds one from this, so they are stripped.
  */
  const reactId = useId();
  const diagramId = `mermaid-${reactId.replace(/[^a-zA-Z0-9_-]/g, "")}`;

  useEffect(() => {
    let cancelled = false;

    (async () => {
      try {
        const mermaid = (await import("mermaid")).default;
        mermaid.initialize({
          startOnLoad: false,
          // The page is dark and Mermaid's default theme is not; "base" plus these overrides is
          // the only way to get it to use the app's own palette rather than its own.
          theme: "base",
          darkMode: true,
          securityLevel: "strict",
          fontFamily: "ui-sans-serif, -apple-system, system-ui, sans-serif",
          themeVariables: {
            background: "#141518",
            primaryColor: "#1a1c20",
            primaryTextColor: "#f0f1f3",
            primaryBorderColor: "#33373d",
            lineColor: "#6a7078",
            secondaryColor: "#22252a",
            tertiaryColor: "#1e2740",
            noteBkgColor: "#22252a",
            noteTextColor: "#9aa0a8",
            noteBorderColor: "#33373d",
          },
        });

        const { svg: rendered } = await mermaid.render(diagramId, chart);
        if (!cancelled) setSvg(rendered);
      } catch {
        // A diagram that will not parse is a typo in the note, not a broken page. Show the
        // source so it can be read and corrected.
        if (!cancelled) setFailed(true);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [chart, diagramId]);

  if (failed) {
    return (
      <div className="my-3 overflow-x-auto rounded-card border border-line bg-surface-2 px-3.5 py-3">
        <p className="mb-2 text-[11px] uppercase tracking-wide text-warn">
          Diagram could not be drawn — showing the source
        </p>
        <pre className="font-mono text-[12.5px] leading-relaxed text-ink-dim">{chart}</pre>
      </div>
    );
  }

  if (!svg) {
    return (
      <div className="my-3 rounded-card border border-dashed border-line px-3.5 py-6 text-center text-[12px] text-ink-faint">
        Drawing diagram…
      </div>
    );
  }

  return (
    <div
      className="my-3 overflow-x-auto rounded-card border border-line bg-surface-2 px-3.5 py-3 [&_svg]:mx-auto [&_svg]:h-auto [&_svg]:max-w-full"
      // Generated by Mermaid from the fence's source, not taken from it.
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
